### ISSUE TITLE
Стиля списков нет

### ISSUE THREAD

**Issue by holopig** [tony-chupak/bitd#5]
https://tony-chupak.github.io/bitd/build/4_inner.html вот тут
Если я создаю `<ul><li>` то там точек нет, глянь шаблон

**Comment by tony-chupak** [comment]
так надо дать классы, такие же как используются в списке на этой странице

**Comment by holopig** [comment]
Тогда добавь туда пример списка а то я же не знаю какие классы :) и закрывай тикет
